/**
 * Unserious-but-motivational one-liners for the athlete home page.
 * One is picked per calendar day (seeded hash), so everyone gets a fresh
 * line each morning without any storage.
 */
export const QUOTES: string[] = [
  "New day, same delulu — but make it gains.",
  "Be the main character. Main characters don't skip leg day.",
  "Your excuses called. Left them on read.",
  "Sweat now, flex later. That's the whole business model.",
  "Gym pass? More like glow-up subscription.",
  "You're one workout away from a better mood. Science, bestie.",
  "Lift heavy, nap hard, repeat. Balanced lifestyle fr.",
  "The bar doesn't care about your vibes. Pick it up anyway.",
  "POV: future you is already thanking present you.",
  "Cardio is just running from mediocrity.",
  "No cap, the hardest set is putting your shoes on.",
  "Slay the sets, then hydrate like it's your side hustle.",
  "Today's forecast: 100% chance of gains.",
  "Rest days are for plotting your comeback arc.",
  "It's giving progress. Keep it giving.",
  "You didn't come this far to only come this far, bestie.",
  "Muscles are just loyalty points from the gym.",
  "Don't ghost your goals. They know where you live.",
  "Be so consistent it's lowkey concerning.",
  "The pump is temporary. The screenshots are forever.",
  "Squat like nobody's judging. They're not — they're tired too.",
  "Every rep is a plot twist in your glow-up story.",
  "Your comfort zone left the chat.",
  "Manifesting? Cute. Lifting? Effective.",
  "Fitness era loading… do not close the app.",
  "Small wins stack like plates. Keep stacking.",
  "You vs. you. Spoiler: you win either way.",
  "That post-workout feeling? Legal happiness hack.",
  "Do it tired. Do it grumpy. Just don't do it tomorrow.",
  "Big back energy only.",
  "Discipline is just self-love with a gym membership.",
  "Your future self is watching through the mirror. Wave.",
  "Run your race. Preferably literally, it's cardio day.",
  "One more rep is basically free character development.",
  "Skipping warm-up is a red flag. Be a green flag.",
  "Consistency > motivation. Motivation sleeps in.",
  "You can't spell legendary without leg day. Don't check that.",
  "Water, protein, sleep — the holy trinity, no debate.",
  "Let the gains do the talking. They're loud.",
  "Progress pics or it still happened. Keep going.",
  "The gym is your villain origin story, but make it wholesome.",
  "Chase goals, not vibes. Okay, chase both.",
  "Certified gym rat behaviour. We love to see it.",
  "Weights before dates.",
  "Your only competition is yesterday's you, and they were kinda weak.",
  "Level up IRL. XP is measured in reps.",
  "It's not sweat, it's your potential leaking out.",
  "Soreness is just your muscles writing a review. 5 stars.",
  "Believe in your delulu, then deadlift it into reality.",
  "Show up scared, leave swole.",
  "The algorithm can't give you abs. The plan can.",
  "Grind quietly. Let the PRs make the noise.",
  "Touch grass AND the squat rack today.",
  "You're not tired, you're pre-strong.",
  "Losing count of reps builds character. Probably.",
  "Warning: side effects include confidence.",
  "Trust the process, tip the process, marry the process.",
  "Every session logged is a receipt for greatness.",
  "Gains don't ghost. Unlike some people.",
  "Do it for the plot. The plot is you, jacked.",
  "Life's short. Your rest between sets shouldn't be.",
  "Vibe check: passed. Form check: coach's problem.",
  "Fall in love with the boring reps. They're loyal.",
  "You're the CEO of getting after it today.",
  "No thoughts, head empty, just one more set.",
  "Strong looks good on you. Wear it daily.",
  "Wake up, be iconic, lift things, sleep. Repeat.",
  "The only bad workout is the imaginary one.",
  "Rizz is temporary. Deadlifts are forever.",
  "Your goals are lowkey obsessed with you. Don't disappoint them.",
  "Turn the pain cave into your happy place. Rent free.",
  "Somebody's watching your grind for motivation. Plot twist: it's you.",
  "Do hard things. Soft blankets after.",
  "Winners recover. Champions foam roll.",
  "Effort is free but the results are priceless.",
  "Your heart rate said 'let's dance'.",
  "Be stronger than your strongest excuse, king/queen.",
  "This workout is sponsored by future-you's confidence.",
  "Streaks aren't just for snap. Protect the workout streak.",
  "You never regret the session. You regret the skip.",
  "Growth mindset? More like growth muscles.",
  "Lock in. The dumbbells miss you.",
  "Coach wrote the plan. Destiny wrote your name on it.",
  "It's leg day somewhere. Unfortunately it's here.",
  "Count your reps, not your doubts.",
  "Real ones train on Mondays too.",
  "Your bed will still be there after the workout. Promise.",
  "Get 1% better today. Compound interest but for biceps.",
  "The grind is unmatched, the playlist is fire, you're unstoppable.",
  "Less scrolling, more swole-ing.",
  "PRs are just high-fives from past you.",
  "Even your excuses are tired of you skipping.",
  "Hot take: you're stronger than you think. Prove it.",
  "Somewhere a barbell whispers your name. Answer it.",
  "Done > perfect. Logged > done.",
  "Stack days like they're W's. Because they are.",
  "You didn't choose the gym life. The gym life chose you.",
  "Finish the session, then act like it was easy.",
  "Entropy wins eventually. Not this set.",
  "Mortality is guaranteed. Quad growth is not.",
  "The void is patient. Your rest timer isn't.",
  "One day you'll be dust. Today, be difficult to kill.",
  "Your skeleton is trapped inside you. Give it better armour.",
  "Existence is temporary. The logbook has receipts.",
  "Outrun your demons. If they keep up, call it tempo work.",
  "The universe is indifferent. The bar is exactly 80 kg.",
  "Train like the apocalypse has a beach episode.",
  "Your ancestors survived winters for this suspiciously specific split.",
  "Nothing matters. Conveniently, that includes your excuses.",
  "Build a body your sleep paralysis demon respects.",
  "The grave can wait. You still have two working sets.",
  "Doom is inevitable. So is progressive overload if you log it.",
  "Today's pain is tomorrow's oddly satisfying spreadsheet.",
  "Become the reason the stairs feel personally attacked.",
  "The abyss stared back and asked if you were done warming up.",
  "Life is short. Use the full range of motion.",
  "You cannot control fate. You can control the eccentric.",
  "Every rep delays your final form by exactly one dramatic montage.",
  "Bad news: time is undefeated. Good news: it skips leg day.",
  "The end is coming. Finish your set first.",
  "Make peace with discomfort. It has already moved in.",
  "Your future ghost wants better posture.",
  "Train now. Haunt the gym later.",
];

/** Deterministic quote-of-the-day: same all day, new tomorrow. */
export function dailyQuote(dateStr: string): string {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) hash = (hash * 31 + dateStr.charCodeAt(i)) >>> 0;
  return QUOTES[hash % QUOTES.length];
}
